postgres: &postgres
  adapter: postgresql
  host: localhost
  port: 5432

development:
  <<: *postgres
  database: notifiable-apns-apnotic-development

test:
  <<: *postgres
  database: notifiable-apns-apnotic-test